# Set up
title: Shanel Wu
logo: #/assets/img/logo.jpg
description: "They/them. HCI researcher and creative technologist. E-textiles, wearables, crafting as praxis and technology."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Owner/author information
owner:
  name:           Shanel Wu
  bio:            "They/them. HCI researcher and creative technologist. E-textiles, wearables, crafting as praxis and technology."
  email:          sminliwu@gmail.com
  github:         sminliwu
  instagram:      pipernell
  location:       "Ottawa, ON"

# collections:

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/blog/page:num/"
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]