# Set up
title: Shanel Shall
logo: #/assets/img/logo.jpg
description: "They/them. PhD student: smart textiles, weaving, computational craft, hardware hacking."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Owner/author information
owner:
  name:           Shanel Wu
  bio:            "They/them. PhD student: smart textiles, weaving, computational craft, hardware hacking."
  email:          shanel.wu@colorado.edu
  twitter:        sminliwu
  github:         sminliwu
  instagram:      pipernell
  location:       "Boulder, CO"

# collections:

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/blog/page:num/"