# Setup
title: Shanel Shall
theme: minimal

# Owner/author information
owner:
  name:           Shanel Wu
  bio:            "Smart textiles."
  email:          shanel.wu@colorado.edu
  github:         sminliwu
  instagram:      pipernell
  location:       "Boulder, CO"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
 paginate: 5
 paginate_path: "blog/page:num"

# Gems
plugins:
  - jekyll-paginate